{% set name = "cmasher" %}
{% set version = "1.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 242e206e58ad6115ff0a5a5405a1ddae80efd1cb03a06dc23db44e710e7c9f23

build:
  number: 0
  noarch: python
  entry_points:
    - cmr = cmasher.cli_tools:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<4.0
  run:
    - colorspacious >=1.1.0
    - e13tools >=0.9.4
    - matplotlib-base >=2.2.4
    - numpy >=1.16.0
    - python >=3.5,<4.0

test:
  imports:
    - cmasher
    - cmasher.tests
  commands:
    - pip check
    - cmr --help
  requires:
    - pip

about:
  home: https://cmasher.readthedocs.io
  summary: Scientific colormaps for making accessible, informative and 'cmashing' plots
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 1313e
