{% set name = "cmasher" %}
{% set version = "1.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c90c2cec87146e3210d3e7f2321fceee38ac7d87c136cd0de25160a14f57ff5

build:
  number: 0
  noarch: python
  entry_points:
    - cmr = cmasher.cli_tools:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - colorspacious >=1.1.0
    - matplotlib-base >=3.5.0
    - numpy >=1.21.2

test:
  source_files:
    - tests
    - conftest.py
  imports:
    - cmasher
  commands:
    - pip check
    - cmr --help
    - pytest -ra tests
  requires:
    - pip
    - pytest
    - pytest-mpl

about:
  home: https://cmasher.readthedocs.io
  summary: Scientific colormaps for making accessible, informative and 'cmashing' plots
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - 1313e
