schema_version: 1

context:
  name: cmasher
  version: "1.9.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: abf76b6e375e9fd4f6c5d5b5afd426bc2e0d926429a3888807b59cae70522e02

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - cmr = cmasher.cli_tools:main

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.11,<5
    - pip
  run:
    - python >=${{ python_min }}
    - colorspacious >=1.1.0
    - matplotlib-base >=3.5.0
    - numpy >=1.21.2

tests:
  - python:
      imports:
        - cmasher
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - files:
      source:
        - tests
        - conftest.py
    requirements:
      run:
        - pip
        - pytest
        - pytest-mpl
        - python ${{ python_min }}.*
    script:
      - cmr --help
      - pytest -ra tests

about:
  summary: Scientific colormaps for making accessible, informative and 'cmashing' plots
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://cmasher.readthedocs.io

extra:
  recipe-maintainers:
    - neutrinoceros
    - 1313e
