schema_version: 1

context:
  name: cmasher
  version: "1.9.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: e372f716205c83b5eb4d167e553a8f24527a8473c33df01b2f3aa20819eae22c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - cmr = cmasher.cli_tools:main

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.11.0,<5
    - pip
  run:
    - python >=${{ python_min }}
    - colorspacious >=1.1.2
    - matplotlib-base >=3.6.0
    - numpy >=1.23.2
    - typing-extensions >=4.4.0

tests:
  - python:
      imports:
        - cmasher
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - files:
      source:
        - tests
        - conftest.py
    requirements:
      run:
        - pip
        - pytest
        - pytest-mpl
        - python ${{ python_min }}.*
    script:
      - cmr --help
      - pytest -ra tests

about:
  summary: Scientific colormaps for making accessible, informative and 'cmashing' plots
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://cmasher.readthedocs.io

extra:
  recipe-maintainers:
    - neutrinoceros
    - 1313e
